name: Prueba Unitaria

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Ejecutar prueba unitaria
        run: |
          pip install pytest
          python -m unittest discover test
